version: '2.1'
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v30-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - dependencies-v30-{{ checksum "project/plugins.sbt" }}
            - dependencies-v30
      - restore_cache:
          keys:
            - target-v30-{{ .Branch }}
            - target-v30
      - run: sbt test
# For some reason, sbt-scoverage doesn't work with sbt 1.3.*
#      - run: sbt coverage test coverageReport
#      - run: bash <(curl -s https://codecov.io/bash) -Z
      - save_cache:
          paths:
            - target
          key: target-v30-{{ .Branch }}
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt
          key: dependencies-v30-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
